name: Node - Azure WebApp CD workflow
on:
  workflow_call:
    inputs:
      acr-name:
        description: 'Azure Container Registry name.'
        required: true
        type: string
      shared-rg-name:
        description: 'Shared resource group name.'
        required: true
        type: string
      rg-name:
        description: 'Resource group name.'
        required: true
        type: string
      jobs-container-name:
        description: 'Container App name.'
        required: true
        type: string
      docker-image-tag:
        description: 'Docker image tag.'
        required: true
        type: string
    secrets:
      env-vars:
        description: 'Environment variables to be set in .env file.'
        required: false
      azure-tenant-id:
        description: ''
        required: true
      azure-client-id:
        description: ''
        required: true
      azure-shared-subscription-id:
        description: ''
        required: true
      azure-subscription-id:
        description: ''
        required: true

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.azure-tenant-id }}
          client-id: ${{ secrets.azure-client-id }}
          subscription-id: ${{ secrets.azure-shared-subscription-id }}

      - name: Create .env file
        run: |
          IFS=',' read -r -a ENV_VARS <<< "${{ secrets.env-vars }}"
          for i in "${ENV_VARS[@]}"; do
            KEY=$(echo $i | cut -f1 -d=)
            VALUE=$(echo $i | cut -f2 -d=)
            echo "$KEY=$VALUE" >> .env
          done

      - name: Build Docker image
        run: az acr build -r ${{ inputs.acr-name }} -g ${{ inputs.shared-rg-name }} -f Dockerfile -t ${{ inputs.docker-image-tag }} . --platform linux/amd64

      - name: Change subscription
        run: az account set -s ${{ secrets.azure-subscription-id }}

      - name: Update the ContainerApp
        run: az containerapp update -n ${{ inputs.jobs-container-name }} -g ${{ inputs.rg-name }} --image ${{ inputs.docker-image-tag }}
