name: Node - Azure IAC CD workflow
on:
  workflow_call:
    inputs:
      allowed-dirs:
        description: "Directories where Cloud functions are located. Split by comma."
        required: true
        type: string
      acr-name:
        description: "Azure Container Registry name."
        required: true
        type: string
      shared-rg-name:
        description: "Shared resource group name."
        required: true
        type: string
      rg-name:
        description: "Resource group name."
        required: true
        type: string
      environment:
        description: "Environment name."
        required: true
        type: string
      runner:
        description: "Runner for github action"
        required: false
        type: string
    secrets:
      env-vars:
        description: "Environment variables to be set in .env file in a JSON format."
        required: true
      azure-tenant-id:
        description: ""
        required: true
      azure-client-id:
        description: ""
        required: true
      azure-shared-subscription-id:
        description: ""
        required: true
      azure-subscription-id:
        description: ""
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changes:
    name: Look for changes in Cloud Functions
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.filter.outputs.directories }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check changed files
        id: diff
        run: |
          if [ $GITHUB_BASE_REF ]; then
            # Pull Request
            git fetch origin $GITHUB_BASE_REF --depth=1
            export DIFF=$( git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA )
            echo "Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA"
          else
            # Push
            git fetch origin ${{ github.event.before }} --depth=1
            export DIFF=$( git diff --diff-filter=d --name-only ${{ github.event.before }} $GITHUB_SHA )
            echo "Diff between ${{ github.event.before }} and $GITHUB_SHA"
          fi
          echo "$DIFF"
          # Escape newlines (replace \n with %0A)
          echo "diff=$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )" >> $GITHUB_OUTPUT

      - name: Set matrix for build
        id: filter
        run: |
          DIFF="${{ steps.diff.outputs.diff }}"
          DIFF=$(printf '%b' "${DIFF//%0A/$'\n'}")

          if [ -z "$DIFF" ]; then
            echo "directories=[]" >> $GITHUB_OUTPUT
          else
            JSON="["
            # Loop by lines
            while read path; do

            # Set $directory to substring before third /
            directory="$( echo $path | cut -d'/' -f1-2 -s )"

            # only allow directories specified in allowed-dirs
            IFS=',' read -ra ALLOWED <<< "${{ inputs.allowed-dirs }}"
            for i in "${ALLOWED[@]}"; do
              if [[ "$directory" == "$i"* ]]; then
                # Add build to the matrix only if it is not already included
                JSONline="\"$directory\","

                if [[ "$JSON" != *"$JSONline"* ]]; then
                  JSON="$JSON$JSONline"
                fi
              fi
            done
            done <<< "$DIFF"

            # Remove last "," and add closing brackets
            if [[ $JSON == *, ]]; then
              JSON="${JSON%?}"
            fi
            JSON="$JSON]"
            echo $JSON

            # Set output
            echo "directories=$( echo "$JSON" )" >> $GITHUB_OUTPUT
          fi

  build-and-deploy:
    name: Build and Deploy
    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}

    needs: changes
    if: ${{ needs.changes.outputs.directories != '[]' && needs.changes.outputs.directories != '' }}
    strategy:
      matrix:
        directory: ${{ fromJSON(needs.changes.outputs.directories) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v3
        with:
          tenant-id: ${{ secrets.azure-tenant-id }}
          client-id: ${{ secrets.azure-client-id }}
          subscription-id: ${{ secrets.azure-shared-subscription-id }}

      - name: Create .env file
        run: |
          echo '${{ secrets.env-vars }}' > secrets.json
          ENV_CONFIGURATION=$(jq -r ".\"${{ matrix.directory }}\"" secrets.json)

          # Parse the JSON object and write keys and values to the .env file
          echo "$ENV_CONFIGURATION" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' > ${{ matrix.directory }}/.env

      - name: Resolve a Docker image with incremented tag
        run: |
          DOCKER_IMAGE_TAG=$(jq -r ".\"docker-image-tags\".\"${{ inputs.environment }}\"" ${{ matrix.directory }}/azure/config.json)
          echo $DOCKER_IMAGE_TAG

          # Retrieve the latest Docker image tag from ACR
          LATEST_TAG=$(az acr repository show-tags --name ${{ inputs.acr-name }} --repository $DOCKER_IMAGE_TAG --orderby time_desc --output tsv | head -n 1)

          # Check if LATEST_TAG is empty or not
          if [ -z "$LATEST_TAG" ]
          then
            # If LATEST_TAG is empty, default VERSION_NUMBER to 0
            VERSION_NUMBER=0
          else
            # If LATEST_TAG is not empty, check if it's a number
            if [[ $LATEST_TAG =~ ^[0-9]+$ ]]
            then
              # If LATEST_TAG is a number, extract the version number
              VERSION_NUMBER=$LATEST_TAG
            else
              # If LATEST_TAG is not a number, default VERSION_NUMBER to 0
              VERSION_NUMBER=0
            fi
          fi                

          # Increment the version number
          NEW_VERSION_NUMBER=$((VERSION_NUMBER + 1))

          # Build the Docker image with the new tag
          NEW_DOCKER_IMAGE_TAG="$DOCKER_IMAGE_TAG:$NEW_VERSION_NUMBER"

          echo $NEW_DOCKER_IMAGE_TAG

          # Set the new Docker image tag as an environment variable for subsequent steps
          echo "DOCKER_IMAGE_TAG=$NEW_DOCKER_IMAGE_TAG" >> $GITHUB_ENV

      - name: Resolve a Function id
        run: |
          FUNCTION_ID=$(jq -r ".\"function-ids\".\"${{ inputs.environment }}\"" ${{ matrix.directory }}/azure/config.json)
          echo $FUNCTION_ID
          echo "FUNCTION_ID=$FUNCTION_ID" >> $GITHUB_ENV

      - name: Check if DOCKER_IMAGE_TAG and FUNCTION_ID are set
        run: |
          if [[ -z "${DOCKER_IMAGE_TAG}" || -z "${FUNCTION_ID}" ]]; then
            echo "DOCKER_IMAGE_TAG or FUNCTION_ID is not set. Exiting..."
            exit 1
          fi

      - name: Login to ACR
        shell: bash
        run: |
          az acr login \
              --name ${{ inputs.acr-name }}  \
              --expose-token

      - name: ACR repository list
        run: az acr repository list -n ${{ inputs.acr-name }}

      - name: Build Docker image
        run: az acr build -r ${{ inputs.acr-name }} -g ${{ inputs.shared-rg-name }} -f Dockerfile -t ${{ env.DOCKER_IMAGE_TAG }} . --platform linux/amd64
        working-directory: ${{ matrix.directory }}

      - name: Change subscription
        run: az account set -s ${{ secrets.azure-subscription-id }}

      - name: Set Runtime for FunctionApp
        run: az webapp config set -n ${{ env.FUNCTION_ID }} -g ${{ inputs.rg-name }} --linux-fx-version "DOCKER|${{ inputs.acr-name }}.azurecr.io/${{ env.DOCKER_IMAGE_TAG }}"

      - name: Update the FunctionApp
        run: az functionapp config container set -n ${{ env.FUNCTION_ID }} -g ${{ inputs.rg-name }} --image ${{ inputs.acr-name }}.azurecr.io/${{ env.DOCKER_IMAGE_TAG }}

      - name: Restart the FunctionApp
        run: az functionapp restart -n ${{ env.FUNCTION_ID }} -g ${{ inputs.rg-name }}
