name: Node - Azure WebApp CD workflow
on:
  workflow_call:
    inputs:
      acr-name:
        description: 'Azure Container Registry name.'
        required: true
        type: string
      shared-rg-name:
        description: 'Shared resource group name.'
        required: true
        type: string
      rg-name:
        description: 'Resource group name.'
        required: true
        type: string
      jobs-container-name:
        description: 'Container App name.'
        required: true
        type: string
      environment:
        description: 'Environment name.'
        required: true
        type: string
      runner:
        description: 'Runner for github action'
        required: false
        type: string
    secrets:
      env-vars:
        description: 'Environment variables to be set in .env file.'
        required: false
      azure-tenant-id:
        description: ''
        required: true
      azure-client-id:
        description: ''
        required: true
      azure-shared-subscription-id:
        description: ''
        required: true
      azure-subscription-id:
        description: ''
        required: true

jobs:
  build:
    name: Build and deploy
    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}
    timeout-minutes: 15

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.azure-tenant-id }}
          client-id: ${{ secrets.azure-client-id }}
          subscription-id: ${{ secrets.azure-shared-subscription-id }}

      - name: Create .env file
        run: |
          IFS=';' read -r -a ENV_VARS <<< "${{ secrets.env-vars }}"
          for i in "${ENV_VARS[@]}"; do
            KEY=$(echo $i | cut -f1 -d=)
            VALUE=$(echo $i | cut -f2 -d=)
            echo "$KEY=$VALUE" >> .env
          done

      - name: Resolve a Docker image with incremented tag
        run: |
          DOCKER_IMAGE_TAG=$(jq -r ".\"docker-image-tags\".\"${{ inputs.environment }}\"" azure/config.json)
          echo $DOCKER_IMAGE_TAG
          
          # Retrieve the latest Docker image tag from ACR
          LATEST_TAG=$(az acr repository show-tags --name ${{ inputs.acr-name }} --repository $DOCKER_IMAGE_TAG --orderby time_desc --output tsv | head -n 1)
          
          # Check if LATEST_TAG is empty or not
          if [ -z "$LATEST_TAG" ]
          then
            # If LATEST_TAG is empty, default VERSION_NUMBER to 0
            VERSION_NUMBER=0
          else
            # If LATEST_TAG is not empty, check if it's a number
            if [[ $LATEST_TAG =~ ^[0-9]+$ ]]
            then
              # If LATEST_TAG is a number, extract the version number
              VERSION_NUMBER=$LATEST_TAG
            else
              # If LATEST_TAG is not a number, default VERSION_NUMBER to 0
              VERSION_NUMBER=0
            fi
          fi                
          
          # Increment the version number
          NEW_VERSION_NUMBER=$((VERSION_NUMBER + 1))
          
          # Build the Docker image with the new tag
          NEW_DOCKER_IMAGE_TAG="$DOCKER_IMAGE_TAG:$NEW_VERSION_NUMBER"
          
          echo $NEW_DOCKER_IMAGE_TAG

          # Set the new Docker image tag as an environment variable for subsequent steps
          echo "DOCKER_IMAGE_TAG=$NEW_DOCKER_IMAGE_TAG" >> $GITHUB_ENV

      - name: Login to ACR
        shell: bash
        run: |
          az acr login \
              --name ${{ inputs.acr-name }}  \
              --expose-token

      - name: ACR repository list
        run: az acr repository list -n ${{ inputs.acr-name }}

      - name: Build Docker image
        run: az acr build -r ${{ inputs.acr-name }} -g ${{ inputs.shared-rg-name }} -t ${{ env.DOCKER_IMAGE_TAG }} . --platform linux/amd64

      - name: Change Subscription
        run: az account set -s ${{ secrets.azure-subscription-id }}

      - name: Update the ContainerApp
        run: az containerapp update -n ${{ inputs.jobs-container-name }} -g ${{ inputs.rg-name }} --image ${{ inputs.acr-name }}.azurecr.io/${{ env.DOCKER_IMAGE_TAG }}
