name: Node - Yarn CI workflow
on:
  workflow_call:
    inputs:
      node-version:
        description: 'Set a node version for your workflow.'
        required: true
        type: string
      junit-test-report-path:
        description: 'Select directories where junit report is located (separated by comma).'
        required: true
        type: string
        default: '*/junit.xml'
      junit-test-coverage-configuration:
        description: 'Name and where coverage report file is located (separated by comma). Applicable only if report is not located in coverage/coverage-summary.json folder.'
        required: false
        type: string
    secrets:
      env-vars:
        description: 'Environment variables to be set in .env file.'
        required: false

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}
          cache: 'yarn'

      - name: Create .env file
        run: |
          while IFS= read -r line; do
            lines+=("$line")
          done <<< "${{ secrets.env-vars }}"
          
          for i in "${lines[@]}"; do
            KEY=${i%%=*}
            VALUE=${i#*=}
            echo "$KEY=$VALUE" >> .env
          done

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

  code-quality:
    name: Code quality
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Code quality
        run: yarn lint

  tests:
    name: Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Tests
        run: yarn test:coverage

      - name: Tests Report
        id: test-report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report
          path: ${{inputs.junit-test-report-path}}
          reporter: jest-junit
          fail-on-error: false

      - name: Tests Coverage
        if: success() || failure()
        uses: MishaKav/jest-coverage-comment@main
        with:
          create-new-comment: true
          multiple-files: ${{ inputs.junit-test-coverage-configuration != '' && inputs.junit-test-coverage-configuration || null }}
